### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by mpotter** [ableco/ablecop#17]
We seem to be using eslint outside the context of AbleCop in at least two instances (Core and Fino). I think it would be a good idea to incorporate into AbleCop if we want that linting to be enforced by Pronto, etc.

http://eslint.org/
https://github.com/mmozuras/pronto-eslint

cc @dennmart @joerodrig3

**Comment by joerodrig3** [comment]
@shiau also uses eslint in mighty-client.

**Comment by dennmart** [comment]
I spent some time looking into this, and am a bit stuck.

The runner relies on [eslintrb](https://github.com/zendesk/eslintrb), which seems to be a re-implementation of ESLint but using ExecJS. For regular ol' Javascript, it works well. But since it's using ExecJS, it doesn't any support for the plugins that we're using (like [babel-eslint](https://www.npmjs.com/package/babel-eslint) and [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react)). Any files written in ES6, which we're using more now, can't be linted using eslintrb.

We can set this runner up and only lint regular Javascript files but it feels like it's not worth doing since we won't reap the bulk of the benefit of having this automated.

**Comment by joerodrig** [comment]
I think this can be closed. We can integrate projects with CircleCI and enforce different strictness levels through our webpack configs.
