### ISSUE TITLE
Filenames were appended to .gitignore incorrectly

### ISSUE THREAD

**Issue by blim8183** [ableco/ablecop#3]
When I ran the install command, the filenames were appended to by `.gitignore` like this:

```
.fasterer.yml.rubocop.yml.scss-lint.yml
```

**Comment by blim8183** [comment]
It would be a nice bonus if a comment was added to the `.gitignore` as well that separated the files

**Comment by blim8183** [comment]
Ah, I was using an older version of the gem. Looks like it's putting them on separate lines now. Would still be nice to add the second part.

**Comment by dennmart** [comment]
I had that in place at one time, but removed it because it becomes tricky when we have to add other files to `.gitignore` in the future (when adding a new code analysis runner). We'd have to ensure that AbleCop-related files in `.gitignore` are together for this to work best, and I didn't think the added complexity of trying to group the files together was worth the work.

**Comment by blim8183** [comment]
Ahh, got it. SGTM.
