### ISSUE TITLE
Update some Colors Rules

### ISSUE THREAD

**Issue by paulrrdiaz** [ableco/ablecop#32]
I was working on some improve for our Stylesheets architecture, I found some blockers here, may be someone can give some advice

- [colorkeyword](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorkeyword)
We're using `map-get` functions, we try to keep simple so for error color(usually red) we called `red`
![screen shot 2016-11-09 at 7 06 56 pm](https://cloud.githubusercontent.com/assets/1366028/20184014/43f4934c-a735-11e6-8319-4a0f16ee8ace.png)
so, 😭 

-  [colorvariable](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable)
We're using variables to save all the constants values, but, as I said above, it has some problems when I used `green, red, blue` in `map-get` function.
![screen shot 2016-11-09 at 7 06 13 pm](https://cloud.githubusercontent.com/assets/1366028/20184016/442e6464-a735-11e6-920f-e207a142c37b.png)

So, I propose to set these values to `false`:
```
ColorKeyword:
    enabled: false
ColorVariable:
    enabled: false
```

cc: @jakep @cpenarrieta @DanteCavero

**Comment by cpenarrieta** [comment]
I agree!

**Comment by dennmart** [comment]
I kind of agree with the explanation given on the scss-lint documentation as to why these are set to true by default: https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#colorvariable

However, I honestly don't do a whole lot of front-end work, so I don't have a strong opinion on keeping it set to true, so I'm good with applying these changes :art:

**Comment by jakep** [comment]
Paul and I discussed this the other day. The reasoning behind these linting preferences are correct and accurate. I agree with Dennis that they should be `true` by defaut. I believe the problem is in their regex pattern. I don't believe they account for the way we're writing SCSS.

For example, the `ColorKeyword` preference disallows colors to be referenced by their name, e.g. "blue." However, we're using `map-get($colors, blue)`, which calls a color in [variable map](https://codepen.io/jakealbaugh/post/using-sass-functions-to-access-complex-variable-maps). The linter doesn't account for that pattern and gets upset. `ColorVariable` is balking for similar reasons.

Is it possible to update their pattern to support our syntax usage?

/cc @dennmart @cpenarrieta @paulrrdiaz

**Comment by dennmart** [comment]
@paulrrdiaz @jakep Sorry for the months-long delay in getting back to this (I'm finally getting some breathing room to work on AbleCop updates).

There was an interesting discussion about this topic in the scss-lint repo: https://github.com/brigade/scss-lint/issues/175, which is among the same lines as to why the `ColorKeyword` and `ColorVariable` are set by default.

In that discussion, the summary is basically to do one of two things:

- Disable those checks in scss-lint (which is what @paulrrdiaz recommended to begin with).
- Rename the variables into something other than color keywords (for example, instead of using `blue` as a variable, using `blue-default` instead, which won't trigger this error).

I'm good with disabling those checks - if there's a strong preference to do that, let me know and I'll do that quickly. But I just wanted to bring it up the discussion once more because I think that that naming a variable with a known keyword is not a good practice (although to be fair, it might be a perfectly fine practice in CSS / SCSS).

**Comment by paulrrdiaz** [comment]
On my side, I'd rather go through the first option:
```yml
ColorKeyword:
    enabled: false
ColorVariable:
    enabled: false
```
@frontend-3 @raffo1234 @DanteCavero what do you thing about this? 🤔

**Comment by jakep** [comment]
Thanks for looking into it more @dennmart!

In light of that discussion, my suggestion is to keep those two linter checks on. From my understanding, it seems as though Sass will render those colors inaccurately anyway, causing style bugs. Ultimately, it is valid and a good idea to check for the use of color keywords in our CSS.

I also agree with the general statement around using more semantic names (e.g. `error-text` instead of `red`, `secondary-text` instead of `dark-grey`, etc.). However I do see the use case of using a variable like `$black: #444`. In those cases, which should be less common, we should use their suggestion of `black-default` or `black-primary`. Another practice we can explore is defining those colors as their keyword in our config files (e.g. `$black: #444`), then reusing those colors more semantically for specific components (e.g. `$primary-text: $black` and `$dark-background: $black`). There are times when colors are reused for multiple components. It's similar to how Bootstrap inherits color variables in their configs.

cc: @paulrrdiaz, @frontend-3, @DanteCavero

**Comment by frontend-3** [comment]
Hey guys! 

Good discussion ✨. I agree with not disabling those checks as @jakep said, they are accurate and we should keep it. I really like what you guys proposed, the best is use more semantic names and for those cases like `black` or `white` I prefer what @jakep proposed, I think having something like `black-default` doesn’t make sense, so we can declare them as vars and then rename them to a more sematic way.

Note: I jumped here because I was taking a look on https://github.com/brigade/scss-lint/issues/175 and accidentally saw the :able: PR reference. Sorry for dont taking a look before 😢

 cc @dennmart @jakep

**Comment by dennmart** [comment]
Cleaning up stale issues - we can reopen if someone wants to discuss this further but it seems like it was decided to keep the existing linters as they were.
