### ISSUE TITLE
Updating TargetRubyVersion 

### ISSUE THREAD

**Issue by joerodrig** [ableco/ablecop#58]
The TargetRubyVersion to lint on is currently set to [2.2](https://github.com/ableco/ablecop/blob/master/config/.rubocop.yml#L64)

There are some performance improvements and changes introduced in later Ruby versions that I think we may want to support(ie. `frozen_string_literals`). 

Are there any plans to bump up the minimum Ruby version being used? I believe the oldest Ruby version currently used on projects is `2.3.2`

**Comment by dennmart** [comment]
I created a pull request (#59) that does just this. Thanks for suggesting it!

One interesting thing that I noticed when checking [RuboCop's default configuration](https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L115-L121) is that if `TargetRubyVersion` isn't set in the configuration, it checks if `.ruby-version` exists and specifies a valid Ruby version and uses that version when running. We might want to standardize that instead of specifying `TargetRubyVersion` in the configuration in the future.
